[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/carrotflakes/benihora"

[dependencies]
nih_plug_xtask = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "eb968ba44666d96cb2349ad877fcdcbccb993f8c" }
